version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/users
      - SPRING_DATASOURCE_USERNAME=postgresql
      - SPRING_DATASOURCE_PASSWORD=postgresql_password
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
      - API_SECURITY_TOKEN_SECRET=secret_value
      - API_SECURITY_TOKEN_EXPIRATION=2
      - ADMIN_EMAIL=admin@example.com
      - ADMIN_PASSWORD=adminP@ssw0rd123
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: users
      POSTGRES_USER: postgresql
      POSTGRES_PASSWORD: postgresql_password
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"
